sudo: required

dist: trusty

language: node_js

node_js:
  - "10"
  - "9"
  - "8"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update -qq
  - sudo apt-get install geth -y -qq
  - yes | geth --rpcapi eth,web3,personal --rpc --dev &

after_script:
  - killall geth